# This rule is not used by the project capa-eni-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the networking.dcn.ssu.ac.kr.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: capa-eni-controller
    app.kubernetes.io/managed-by: kustomize
  name: enipool-editor-role
rules:
- apiGroups:
  - networking.dcn.ssu.ac.kr
  resources:
  - enipools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.dcn.ssu.ac.kr
  resources:
  - enipools/status
  verbs:
  - get
