---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusters
  - machines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - awsclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - awsmachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - awsmachines/finalizers
  verbs:
  - update
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - awsmachines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.dcn.ssu.ac.kr
  resources:
  - eniclaims
  - enipools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.dcn.ssu.ac.kr
  resources:
  - eniclaims/finalizers
  - enipools/finalizers
  verbs:
  - update
- apiGroups:
  - networking.dcn.ssu.ac.kr
  resources:
  - eniclaims/status
  - enipools/status
  verbs:
  - get
  - patch
  - update
